# Generated by Django 2.1 on 2019-05-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20190427_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(blank=True, max_length=100)),
                ('article', models.CharField(blank=True, max_length=10000)),
                ('image', models.ImageField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
