# Generated by Django 2.1 on 2019-05-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_articles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
