# Generated by Django 2.1 on 2019-05-28 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_articles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
