# Generated by Django 2.1 on 2019-05-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_articles_login_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_article', models.TextField(max_length=50)),
            ],
            options={
                'db_table': 'article_comment',
            },
        ),
    ]
