# Generated by Django 2.1 on 2019-06-03 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20190603_0457'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='register_author',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='register_author',
            name='last_login',
        ),
    ]
