# Generated by Django 2.1 on 2019-06-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20190603_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_comment',
            name='approved_comment',
            field=models.BooleanField(default=False),
        ),
    ]
